spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: forms_back

  docker:
    compose:
      enabled: false

  datasource:
    url: ${MY_DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MY_USER}
    password: ${MY_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: true
    change-log: db/changelog/log.xml

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

