spring:
  application:
    name: forms_back

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mariadb://localhost:3306/${MY_DB}
    driver-class-name: org.mariadb.jdbc.Driver
    username: pedro
    password: ${MY_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: db/changelog/log.xml

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

