spring:
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: forms_back

  docker:
    compose:
      enabled: false

  datasource:
    url: ${MY_DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MY_USER}
    password: ${MY_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 150
        order_inserts: true
        order_updates: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: db/changelog/log.xml

  logging:
    level:
      org.springframework.web: DEBUG

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

