package agoraa.app.forms_back.dto.product

import agoraa.app.forms_back.enums.MipsCategoriesEnum
import agoraa.app.forms_back.enums.SectorsEnum
import agoraa.app.forms_back.enums.StoresEnum
import agoraa.app.forms_back.suppliers.suppliers.model.SupplierModel
import java.time.LocalDate

data class ProductDto(
    val id: Long,
    val code: String,
    val name: String,
    var supplier: SupplierModel? = null,
    val isResource: Boolean,
    val barcode: String,
    val store: StoresEnum,
    val outOfMix: Boolean,
    val sector: SectorsEnum,
    val weight: String,
    val minimumStock: Int,
    val salesLastThirtyDays: Double,
    val salesLastTwelveMonths: Double,
    val salesLastSevenDays: Double,
    val averageSalesLastThirtyDays: Double,
    val openOrder: Double,
    val averageSalesLastThirtyDaysTwelveMonths: Double,
    val averageExpiration: Double,
    val dailySales: Float,
    val lastCost: Float,
    val exchangeQuantity: Float,
    val lossQuantity: Float,
    val networkStock: Float,
    val transferPackage: Int,
    val promotionQuantity: Float,
    val noDeliveryQuantity: Int,
    val dailySalesAmount: Float,
    val daysToExpire: Float,
    val salesProjection: Float,
    val inProjection: Int,
    val excessStock: Float,
    val term: String,
    val currentStockPerPackage: String,
    val averageSales: Float,
    val availableStock: Float,
    val groupName: String? = null,
    val subgroup: String? = null,
    val brand: String? = null,
    val packageQuantity: Int,
    val currentStock: Double? = null,
    val expirationDate: LocalDate? = null,
    val promotionType: String? = null,
    val flag1: String? = null,
    val flag2: String? = null,
    val flag3: String? = null,
    val flag4: String? = null,
    val flag5: String? = null,
    val category: String? = null,
    val highestSales: Double? = null,
    val totalCost: Float? = null,
    val totalSales: Float? = null,
    val costP: Float? = null,
    val salesP: Float? = null,
    val stockTurnover: Float? = null,
    val netCost: Double? = null,
    val salesPrice: Float? = null,
    val salesPrice2: Float? = null,
    val promotionPrice: Float? = null,
    val mipCategory: MipsCategoriesEnum? = null,
)
