package agoraa.app.forms_back.dto.product

import agoraa.app.forms_back.dto.supplier.SupplierDto
import agoraa.app.forms_back.enum.StoresEnum
import com.fasterxml.jackson.annotation.JsonInclude
import java.time.LocalDate

@JsonInclude(JsonInclude.Include.NON_NULL)
data class ProductDto(
    val id: Long,
    var code: String? = null,
    var name: String? = null,
    var barcode: String? = null,
    var store: StoresEnum? = null,
    var outOfMix: Boolean? = null,
    var sector: String? = null,
    var groupName: String? = null,
    var subgroup: String? = null,
    var brand: String? = null,
    var supplier: SupplierDto? = null,
    var weight: String? = null,
    var packageQuantity: Int? = null,
    var minimumStock: Int? = null,
    var salesLast30Days: Float? = null,
    var salesLast12Months: Float? = null,
    var salesLast7Days: Float? = null,
    var dailySales: Float? = null,
    var lastCost: Float? = null,
    var averageSalesLast30Days: Float? = null,
    var currentStock: Float? = null,
    var openOrder: Float? = null,
    var expirationDate: LocalDate? = null,
    var lossQuantity: Float? = null,
    var promotionType: String? = null,
    var exchangeQuantity: Float? = null,
    var flag1: String? = null,
    var flag2: String? = null,
    var flag3: String? = null,
    var flag4: String? = null,
    var flag5: String? = null,
    var averageExpiration: Float? = null,
    var networkStock: Float? = null,
    var transferPackage: Int? = null,
    var promotionQuantity: Float? = null,
    var category: String? = null,
    var noDeliveryQuantity: Int? = null,
    var averageSales30d12m: Float? = null,
    var highestSales: Float? = null,
    var dailySalesAmount: Float? = null,
    var daysToExpire: Float? = null,
    var salesProjection: Float? = null,
    var inProjection: Int? = null,
    var excessStock: Float? = null,
    var totalCost: Float? = null,
    var totalSales: Float? = null,
    var term: String? = null,
    var currentStockPerPackage: String? = null,
    var averageSales: Float? = null,
    var costP: Float? = null,
    var salesP: Float? = null,
    var availableStock: Float? = null,
    var stockTurnover: Float? = null,
    var netCost: Float? = null,
    var salesPrice: Float? = null,
    var salesPrice2: Float? = null,
    var promotionPrice: Float? = null
)