package agoraa.app.forms_back.dto.product

import agoraa.app.forms_back.enum.MipsCategoriesEnum
import agoraa.app.forms_back.enum.SectorsEnum
import agoraa.app.forms_back.enum.StoresEnum
import agoraa.app.forms_back.model.suppliers.SupplierModel
import com.fasterxml.jackson.annotation.JsonInclude
import java.time.LocalDate

data class ProductDto(
    val id: Long,
    val code: String,
    val name: String,
    var supplier: SupplierModel? = null,
    val isResource: Boolean,
    val barcode: String,
    val store: StoresEnum,
    val outOfMix: Boolean,
    val sector: SectorsEnum,
    val weight: String,
    val minimumStock: Int,
    val salesLast30Days: Float,
    val salesLast12Months: Float,
    val salesLast7Days: Float,
    val dailySales: Float,
    val lastCost: Float,
    val averageSalesLast30Days: Float,
    val openOrder: Float,
    val exchangeQuantity: Float,
    val lossQuantity: Float,
    val averageExpiration: Float,
    val networkStock: Float,
    val transferPackage: Int,
    val promotionQuantity: Float,
    val noDeliveryQuantity: Int,
    val averageSales30d12m: Float,
    val dailySalesAmount: Float,
    val daysToExpire: Float,
    val salesProjection: Float,
    val inProjection: Int,
    val excessStock: Float,
    val term: String,
    val currentStockPerPackage: String,
    val averageSales: Float,
    val availableStock: Float,
    val groupName: String? = null,
    val subgroup: String? = null,
    val brand: String? = null,
    val packageQuantity: Int? = null,
    val currentStock: Float? = null,
    val expirationDate: LocalDate? = null,
    val promotionType: String? = null,
    val flag1: String? = null,
    val flag2: String? = null,
    val flag3: String? = null,
    val flag4: String? = null,
    val flag5: String? = null,
    val category: String? = null,
    val highestSales: Float? = null,
    val totalCost: Float? = null,
    val totalSales: Float? = null,
    val costP: Float? = null,
    val salesP: Float? = null,
    val stockTurnover: Float? = null,
    val netCost: Float? = null,
    val salesPrice: Float? = null,
    val salesPrice2: Float? = null,
    val promotionPrice: Float? = null,
    val mipCategory: MipsCategoriesEnum? = null,
)
