package agoraa.app.forms_back.schema.product

import agoraa.app.forms_back.enum.SectorsEnum
import java.time.LocalDate

data class ProductEditSchema(
    val code: String? = null,
    val supplier: String? = null,
    val name: String? = null,
    val barcode: String? = null,
    val outOfMix: Boolean? = null,
    val weight: String? = null,
    val sector: SectorsEnum? = null,
    val groupName: String? = null,
    val subgroup: String? = null,
    val packageQuantity: Int? = null,
    val minimumStock: Int? = null,
    val salesLast30Days: Float? = null,
    val salesLast12Months: Float? = null,
    val salesLast7Days: Float? = null,
    val dailySales: Float? = null,
    val lastCost: Float? = null,
    val averageSalesLast30Days: Float? = null,
    val currentStock: Float? = null,
    val openOrder: Float? = null,
    val expirationDate: LocalDate? = null,
    val lossQuantity: Float? = null,
    val promotionType: String? = null,
    val brand: String? = null,
    val exchangeQuantity: Float? = null,
    val flag1: String? = null,
    val flag2: String? = null,
    val flag3: String? = null,
    val flag4: String? = null,
    val flag5: String? = null,
    val averageExpiration: Float? = null,
    val networkStock: Float? = null,
    val transferPackage: Int? = null,
    val promotionQuantity: Float? = null,
    val category: String? = null,
    val noDeliveryQuantity: Int? = null,
    val averageSales30d12m: Float? = null,
    val highestSales: Float? = null,
    val dailySalesAmount: Float? = null,
    val daysToExpire: Float? = null,
    val salesProjection: Float? = null,
    val inProjection: Int? = null,
    val excessStock: Float? = null,
    val totalCost: Float? = null,
    val totalSales: Float? = null,
    val term: String? = null,
    val currentStockPerPackage: String? = null,
    val averageSales: Float? = null,
    val costP: Float? = null,
    val salesP: Float? = null,
    val availableStock: Float? = null,
    val stockTurnover: Float? = null,
    val netCost: Float? = null,
    val salesPrice: Float? = null,
    val salesPrice2: Float? = null,
    val promotionPrice: Float? = null
)