package agoraa.app.forms_back.schema.product

import agoraa.app.forms_back.enum.MipsCategoriesEnum
import agoraa.app.forms_back.enum.SectorsEnum
import agoraa.app.forms_back.enum.StoresEnum
import java.time.LocalDate

data class ProductSchema(
    val code: String,
    val name: String,
    val supplier: String,
    val barcode: String,
    val store: StoresEnum,
    val outOfMix: Boolean,
    val weight: String,
    val sector: SectorsEnum,
    val groupName: String?,
    val subgroup: String?,
    val packageQuantity: Int,
    val minimumStock: Int,
    val salesLastThirtyDays: Double,
    val salesLastTwelveMonths: Double,
    val salesLastSevenDays: Double,
    val dailySales: Float,
    val lastCost: Float,
    val averageSalesLastThirtyDays: Double,
    val averageSalesThirtyDaysTwelveMonths: Double,
    val currentStock: Double?,
    val openOrder: Double,
    val expirationDate: LocalDate?,
    val lossQuantity: Float,
    val promotionType: String?,
    val brand: String?,
    val exchangeQuantity: Float,
    val flag1: String?,
    val flag2: String?,
    val flag3: String?,
    val flag4: String?,
    val flag5: String?,
    val averageExpiration: Double,
    val networkStock: Float,
    val transferPackage: Int,
    val promotionQuantity: Float,
    val category: String?,
    val noDeliveryQuantity: Int,
    val highestSales: Double?,
    val dailySalesAmount: Float,
    val daysToExpire: Float,
    val salesProjection: Float,
    val inProjection: Int,
    val excessStock: Float,
    val totalCost: Float?,
    val totalSales: Float?,
    val term: String,
    val currentStockPerPackage: String,
    val averageSales: Float,
    val costP: Float?,
    val salesP: Float?,
    val availableStock: Float,
    val stockTurnover: Float?,
    val netCost: Double?,
    val salesPrice: Float?,
    val salesPrice2: Float?,
    val promotionPrice: Float?,
    val mipCategory: MipsCategoriesEnum?,
)