package agoraa.app.forms_back.schema.product

import agoraa.app.forms_back.enums.StoresEnum
import java.time.LocalDate

data class ProductDTO(
    val id: Long,
    val code: String,
    val name: String,
    val supplier: String,
    val barcode: String,
    val store: StoresEnum,
    val outOfMix: Boolean,
    val weight: String,
    val sector: String,
    val groupName: String?,
    val subgroup: String?,
    val packageQuantity: Int?,
    val minimumStock: Int,
    val salesLast30Days: Float,
    val salesLast12Months: Float,
    val salesLast7Days: Float,
    val dailySales: Float,
    val lastCost: Float,
    val averageSalesLast30Days: Float,
    val currentStock: Float?,
    val openOrder: Float,
    val expirationDate: LocalDate?,
    val lossQuantity: Float,
    val promotionType: String?,
    val brand: String?,
    val exchangeQuantity: Float,
    val flag1: String?,
    val flag2: String?,
    val flag3: String?,
    val flag4: String?,
    val flag5: String?,
    val averageExpiration: Float,
    val networkStock: Float,
    val transferPackage: Int,
    val promotionQuantity: Float,
    val category: String?,
    val noDeliveryQuantity: Int,
    val averageSales30d12m: Float,
    val highestSales: Float?,
    val dailySalesAmount: Float,
    val daysToExpire: Float,
    val salesProjection: Float,
    val inProjection: Int,
    val excessStock: Float,
    val totalCost: Float?,
    val totalSales: Float?,
    val term: String,
    val currentStockPerPackage: String,
    val averageSales: Float,
    val costP: Float?,
    val salesP: Float?,
    val availableStock: Float,
    val stockTurnover: Float?,
    val netCost: Float?,
    val salesPrice: Float?,
    val salesPrice2: Float?,
    val promotionPrice: Float?
)
