package agoraa.app.forms_back.products.products.dto.request

import agoraa.app.forms_back.shared.enums.ProductGroupsEnum
import agoraa.app.forms_back.suppliers.suppliers.model.SupplierModel
import java.time.LocalDate

data class ProductsRequestAnticipation(
    val code: String,
    val name: String,
    val supplier: SupplierModel,
    val barcode: String,
    val store: agoraa.app.forms_back.shared.enums.StoresEnum,
    val outOfMix: Boolean,
    val weight: String,
    val sector: agoraa.app.forms_back.shared.enums.ProductSectorsEnum,
    val groupName: ProductGroupsEnum?,
    val subgroup: String?,
    val packageQuantity: Int,
    val minimumStock: Int,
    val salesLastThirtyDays: Double,
    val salesLastTwelveMonths: Double,
    val salesLastSevenDays: Double,
    val dailySales: Float,
    val lastCost: Float,
    val averageSalesLastThirtyDays: Double,
    val averageSalesThirtyDaysTwelveMonths: Double,
    val currentStock: Double?,
    val openOrder: Double,
    val expirationDate: LocalDate?,
    val lossQuantity: Float,
    val promotionType: String?,
    val brand: String?,
    val exchangeQuantity: Float,
    val flag1: String?,
    val flag2: String?,
    val flag3: String?,
    val flag4: String?,
    val flag5: String?,
    val averageExpiration: Double,
    val networkStock: Float,
    val transferPackage: Int,
    val promotionQuantity: Float,
    val category: String?,
    val noDeliveryQuantity: Int,
    val highestSales: Double?,
    val dailySalesAmount: Float,
    val daysToExpire: Float,
    val salesProjection: Float,
    val inProjection: Int,
    val excessStock: Float,
    val totalCost: Float?,
    val totalSales: Float?,
    val term: String,
    val currentStockPerPackage: String,
    val averageSales: Float,
    val costP: Float?,
    val salesP: Float?,
    val availableStock: Float,
    val stockTurnover: Float?,
    val netCost: Double?,
    val salesPrice: Float?,
    val salesPrice2: Float?,
    val promotionPrice: Float?,
    val mipCategory: agoraa.app.forms_back.shared.enums.MipsCategoriesEnum?,
    val isResource: Boolean
)
